version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - .:/var/www/html
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=value
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
